//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace smartfarmmodel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_Animal
    {
        public int ID_Animal { get; set; }
        public string Raca { get; set; }
        public string Filiacao { get; set; }
        public string Classificacao { get; set; }
        public Nullable<System.DateTime> DataNasc { get; set; }
        public string Box { get; set; }
        public string Registro_animal { get; set; }
    }
}
