//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace smartfarmmodel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_Cargo
    {
        public string Cargo { get; set; }
    
        public virtual tb_Cargo tb_Cargo1 { get; set; }
        public virtual tb_Cargo tb_Cargo2 { get; set; }
    }
}
