//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace smartfarmmodel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_funcionario
    {
        public string Nome { get; set; }
        public string Rg { get; set; }
        public string cpf { get; set; }
        public string Cargo { get; set; }
        public string Registro { get; set; }
        public string Telefone { get; set; }
        public Nullable<System.DateTime> DataNasc { get; set; }
        public int ID { get; set; }
    }
}
