//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace smartfarmmodel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tb_Produção
    {
        public int ID { get; set; }
        public string Registro_animal { get; set; }
        public Nullable<int> Quantidade { get; set; }
        public Nullable<System.DateTime> Data { get; set; }
    }
}
