//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace smartfarmmodel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vacinação
    {
        public int ID_animal { get; set; }
        public string Vacina { get; set; }
        public System.DateTime Data { get; set; }
        public string Registro { get; set; }
    }
}
