//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace model2
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SmartFarmEntities : DbContext
    {
        public SmartFarmEntities()
            : base("name=SmartFarmEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<tb_Animal> tb_Animal { get; set; }
        public virtual DbSet<tb_Cargo> tb_Cargo { get; set; }
        public virtual DbSet<tb_Classificacao> tb_Classificacao { get; set; }
        public virtual DbSet<tb_funcionario> tb_funcionario { get; set; }
        public virtual DbSet<tb_Login> tb_Login { get; set; }
        public virtual DbSet<tb_Medicamentos> tb_Medicamentos { get; set; }
        public virtual DbSet<tb_Producao> tb_Producao { get; set; }
        public virtual DbSet<tb_Proprietario> tb_Proprietario { get; set; }
        public virtual DbSet<tb_Raca> tb_Raca { get; set; }
        public virtual DbSet<tb_Usuario> tb_Usuario { get; set; }
    }
}
