//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace model2
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_Animal
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_Animal()
        {
            this.tb_Producao = new HashSet<tb_Producao>();
        }
    
        public int ID { get; set; }
        public string Raca { get; set; }
        public string Classificacao { get; set; }
        public string Filiacao { get; set; }
        public Nullable<System.DateTime> DataNasc { get; set; }
        public string Alimentacao { get; set; }
        public string Box { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_Producao> tb_Producao { get; set; }
    }
}
