//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace model2
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_Medicamentos
    {
        public int ID { get; set; }
        public string Nome { get; set; }
        public string Tipo { get; set; }
        public string Aplicacao { get; set; }
        public string Contraindicacao { get; set; }
        public string Fabricante { get; set; }
        public string Observacao { get; set; }
    }
}
