//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace model2
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_Producao
    {
        public int ID { get; set; }
        public Nullable<System.DateTime> Periodo { get; set; }
        public Nullable<double> ProdMedia { get; set; }
        public Nullable<double> Qtd { get; set; }
        public Nullable<int> IDAnimal { get; set; }
    
        public virtual tb_Animal tb_Animal { get; set; }
    }
}
