//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace model2
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_Usuario
    {
        public int ID { get; set; }
        public string Nome { get; set; }
        public string CPF { get; set; }
        public string RG { get; set; }
        public string Telefone { get; set; }
        public string Email { get; set; }
        public Nullable<bool> Sexo { get; set; }
        public Nullable<System.DateTime> DataNasc { get; set; }
    
        public virtual tb_funcionario tb_funcionario { get; set; }
        public virtual tb_Proprietario tb_Proprietario { get; set; }
    }
}
